# Generated by Django 5.0.7 on 2024-07-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0003_media_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='order',
        ),
    ]
