# Generated by Django 5.0.7 on 2024-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0005_playlist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='fade_duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='transition_effect',
            field=models.CharField(choices=[('none', 'None'), ('fade', 'Fade')], default='none', max_length=10),
        ),
    ]
